[build]
  command = "cd myapp && CI=false npm install && CI=false npm run build && npm start"
  functions = "myapp" 
  publish = "simple-forum/build" 
  [build.environment]
    REACT_APP_API_URL = "/.netlify/functions"
