databases:
  - name: myapp
    databaseName: myapp
    user: myapp
    plan: free

services:
  - type: web
    name: myapp
    runtime: ruby
    plan: free
     buildCommand: "npm install && bundle install --jobs 4 --retry 3 && npm run build"
      # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
