databases:
  - name: myapp
    databaseName: myapp
    user: myapp
    plan: free

services:
  - type: web
    name: myapp
    runtime: ruby
    plan: free
    buildCommand: |
      cd simple-forum
      npm install
      npm run build
    startCommand: |
      cd myapp
      bundle install
      bundle exec rails db:migrate
      REACT_APP_API_URL=http://localhost:3001/api bundle exec rails server -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
      - key: RAILS_ENV
        value: "production"
